<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/_bootstrap.php';
require_once CERT50_PRIVATE_ROOT . '/app/auth.php';
$admin = require_admin();
$success = flash('success'); $error = flash('error');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Organização — Araucária DX 50 anos</title><link rel="stylesheet" href="../assets/site.css"></head><body>
<header class="site-header"><a class="brand" href="../"><span class="brand-mark">⌁</span><span><strong>ARAUCÁRIA DX</strong><small>GESTÃO · 50 ANOS</small></span></a><a class="admin-link" href="../">Ver consulta pública</a></header>
<main class="admin-shell"><p class="eyebrow">ORGANIZAÇÃO</p><h1>Importar logs e reconhecer participantes</h1><p class="lead">Cada ADIF importado passa a alimentar a consulta pública. Classifique uma operação uma vez e os participantes recebem os endossos automaticamente.</p><nav class="admin-nav"><a href="index.php">Nova importação</a><?php if ($admin['role'] === 'owner'): ?><a href="users.php">Administradores</a><?php endif; ?><a href="logout.php">Sair (<?= h($admin['email']) ?>)</a></nav><?php if ($success): ?><p class="flash"><?= h($success) ?></p><?php endif; ?><?php if ($error): ?><p class="flash danger"><?= h($error) ?></p><?php endif; ?>
<div class="admin-grid"><section class="admin-card"><h2>Nova importação ADIF</h2><p>Os QSOs deste arquivo serão associados aos endossos selecionados abaixo.</p><form action="import.php" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><label class="field">Nome da operação<input name="label" maxlength="180" placeholder="Ex.: 50 anos — etapa 1" required></label><label class="field">Data da atividade<input type="date" name="activity_date"></label></div><label class="field">Arquivo ADIF (.adi ou .adif)<input type="file" name="adif" accept=".adi,.adif,text/plain" required></label><div style="display:flex;gap:18px;flex-wrap:wrap;margin-top:16px"><label class="checkbox"><input type="checkbox" name="satellite" value="1">Contato via satélite</label><label class="checkbox"><input type="checkbox" name="wff" value="1">Ativação WFF</label></div><label class="field">Unidades de conservação<textarea name="activations" placeholder="Uma por linha: PR-0001 | Nome da unidade&#10;Se não houver, deixe em branco."></textarea></label><label class="field">Endossos adicionais<textarea name="endorsements" placeholder="Um por linha: CODIGO | Nome do endosso&#10;Ex.: SAT-QO100 | QO-100"></textarea></label><label class="field">Observações internas<textarea name="notes" placeholder="Opcional — não aparece no diploma."></textarea></label><div class="form-actions"><button type="submit">Importar e publicar nos diplomas</button></div></form></section><aside class="admin-card"><h2>Como funciona</h2><ul><li>Todo QSO recebe o selo “Araucária DX · 50 anos”.</li><li>Marque satélite apenas se a operação tiver esses contatos.</li><li>Informe as unidades de conservação para exibi-las no diploma.</li><li>O ADIF original fica protegido fora de <code>public_html</code>.</li></ul></aside></div></main></body></html>
